#!/usr/bin/env python3
"""Main G-code processor with layer batching optimization.

This is the main entry point for the G-code post-processor that implements
layer batching, collision detection, Z-hop, and prime tower management.
"""

import argparse
import sys
from typing import List, TextIO
from pathlib import Path

from gcode_parser import GCodeParser, GCodeCommand, Layer
from collision_detector import CollisionDetector, NozzleGeometry
from layer_batcher import LayerBatcher
from zhop_manager import ZHopManager, ZHopConfig
from prime_tower import PrimeTowerManager, PrimeTowerConfig


class GCodeProcessor:
    """Main G-code processor with layer batching optimization."""
    
    def __init__(self,
                 nozzle_diameter: float = 0.4,
                 collision_margin: float = 1.0,
                 max_batch_layers: int = 10,
                 zhop_height: float = 0.5,
                 enable_prime_towers: bool = True):
        """
        Initialize G-code processor.
        
        Args:
            nozzle_diameter: Nozzle diameter in mm
            collision_margin: Safety margin for collision detection in mm
            max_batch_layers: Maximum layers to batch together
            zhop_height: Z-hop height in mm
            enable_prime_towers: Enable per-tool prime towers
        """
        # Initialize components
        self.parser = GCodeParser()
        
        # E3D v6 nozzle geometry (from attached image)
        self.nozzle = NozzleGeometry(
            diameter=nozzle_diameter,
            cone_angle=60.0,  # E3D v6 specification
            height=10.0
        )
        
        self.collision_detector = CollisionDetector(self.nozzle, collision_margin)
        self.layer_batcher = LayerBatcher(self.collision_detector, max_batch_layers)
        
        self.zhop_config = ZHopConfig(
            zhop_height=zhop_height,
            enabled=True
        )
        self.zhop_manager = ZHopManager(self.zhop_config)
        
        self.prime_tower_config = PrimeTowerConfig(enabled=enable_prime_towers)
        self.prime_tower_manager = None  # Initialized after parsing
        
        self.current_position = {'x': 0.0, 'y': 0.0, 'z': 0.0}
    
    def process_file(self, input_path: str, output_path: str) -> None:
        """Process a G-code file with layer batching optimization.
        
        Args:
            input_path: Path to input G-code file
            output_path: Path to output G-code file
        """
        print(f"Processing G-code file: {input_path}")
        
        # Parse input file
        print("Parsing G-code...")
        layers = self.parser.parse_file(input_path)
        print(f"Found {len(layers)} layers")
        
        # Determine number of tools
        tools = set(layer.tool for layer in layers if layer.tool is not None)
        num_tools = len(tools)
        print(f"Detected {num_tools} tools: {sorted(tools)}")
        
        # Initialize prime tower manager
        if self.prime_tower_config.enabled and num_tools > 1:
            self.prime_tower_manager = PrimeTowerManager(
                self.prime_tower_config, num_tools
            )
            print(f"Prime towers enabled at positions: {self.prime_tower_manager.get_tower_positions()}")
        
        # Create batches
        print("Creating layer batches...")
        batches = self.layer_batcher.create_batches(layers)
        
        # Print statistics
        stats = self.layer_batcher.get_batch_statistics()
        print("\nBatching Statistics:")
        print(f"  Total layers: {stats['total_layers']}")
        print(f"  Total batches: {stats['total_batches']}")
        print(f"  Tool changes: {stats['tool_changes']}")
        print(f"  Average batch size: {stats['average_batch_size']:.1f} layers")
        print(f"  Maximum batch size: {stats['max_batch_size']} layers")
        print(f"  Batches per tool: {stats['batches_per_tool']}")
        
        # Generate optimized G-code
        print(f"\nGenerating optimized G-code: {output_path}")
        with open(output_path, 'w', encoding='utf-8') as f:
            self._write_optimized_gcode(f, batches)
        
        print("Processing complete!")
    
    def _write_optimized_gcode(self, output: TextIO, batches: List) -> None:
        """Write optimized G-code with batched layers.
        
        Args:
            output: Output file handle
            batches: List of layer batches
        """
        # Write header
        output.write("; G-code optimized with layer batching\n")
        output.write("; Generated by gcode_support_layer_batching\n")
        output.write(";\n")
        
        # Standard initialization
        output.write("G21 ; set units to millimeters\n")
        output.write("G90 ; use absolute coordinates\n")
        output.write("M82 ; use absolute distances for extrusion\n")
        output.write("\n")
        
        current_tool = None
        
        for batch_idx, batch in enumerate(batches):
            output.write(f"; Batch {batch_idx + 1}: Tool T{batch.tool}, "
                        f"Layers {batch.start_layer}-{batch.end_layer} "
                        f"({batch.layer_count()} layers)\n")
            
            # Tool change if needed
            if current_tool != batch.tool:
                output.write(f"T{batch.tool} ; switch to tool {batch.tool}\n")
                current_tool = batch.tool
            
            # Process each layer in the batch
            for layer in batch.layers:
                output.write(f"; Layer {layer.layer_number} at Z={layer.z_height:.3f}\n")
                
                # Synchronize prime towers before printing layer
                if self.prime_tower_manager and layer.layer_number > 1:
                    sync_commands = self.prime_tower_manager.synchronize_towers(
                        batch.tool, layer.layer_number, layer.z_height
                    )
                    for cmd in sync_commands:
                        output.write(f"{cmd.raw_line}\n")
                
                # Print this layer's commands
                for cmd in layer.commands:
                    # Update position tracking
                    if cmd.x is not None:
                        self.current_position['x'] = cmd.x
                    if cmd.y is not None:
                        self.current_position['y'] = cmd.y
                    if cmd.z is not None:
                        self.current_position['z'] = cmd.z
                    
                    output.write(f"{cmd.raw_line}\n")
                
                # Add prime tower for this layer
                if self.prime_tower_manager:
                    tower_commands = self.prime_tower_manager.generate_tower_for_layer(
                        batch.tool, layer.z_height, layer.layer_number
                    )
                    for cmd in tower_commands:
                        output.write(f"{cmd.raw_line}\n")
            
            output.write("\n")
        
        # Write footer
        output.write("; End of optimized G-code\n")
        output.write("M104 S0 ; turn off extruder\n")
        output.write("M140 S0 ; turn off bed\n")
        output.write("G28 X Y ; home X and Y\n")
        output.write("M84 ; disable motors\n")


def main():
    """Main entry point for CLI."""
    parser = argparse.ArgumentParser(
        description='Post-process multi-material G-code with layer batching optimization',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage
  python gcode_processor.py input.gcode output.gcode
  
  # With custom parameters
  python gcode_processor.py input.gcode output.gcode --zhop 0.8 --collision-margin 1.5
  
  # Maximum batching
  python gcode_processor.py input.gcode output.gcode --max-batch-layers 20
        """
    )
    
    parser.add_argument('input', type=str, help='Input G-code file')
    parser.add_argument('output', type=str, help='Output G-code file')
    
    parser.add_argument('--zhop', type=float, default=0.5,
                       help='Z-hop height in mm (default: 0.5)')
    parser.add_argument('--collision-margin', type=float, default=1.0,
                       help='Safety margin for collision detection in mm (default: 1.0)')
    parser.add_argument('--nozzle-diameter', type=float, default=0.4,
                       help='Nozzle diameter in mm (default: 0.4)')
    parser.add_argument('--max-batch-layers', type=int, default=10,
                       help='Maximum layers to batch together (default: 10)')
    parser.add_argument('--disable-prime-towers', action='store_true',
                       help='Disable per-tool prime towers')
    
    args = parser.parse_args()
    
    # Validate input file
    if not Path(args.input).exists():
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        return 1
    
    # Create processor
    processor = GCodeProcessor(
        nozzle_diameter=args.nozzle_diameter,
        collision_margin=args.collision_margin,
        max_batch_layers=args.max_batch_layers,
        zhop_height=args.zhop,
        enable_prime_towers=not args.disable_prime_towers
    )
    
    try:
        processor.process_file(args.input, args.output)
        return 0
    except Exception as e:
        print(f"Error processing G-code: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return 1


if __name__ == '__main__':
    sys.exit(main())
